require 'wongi-engine/filter/filter_test'
require 'wongi-engine/filter/equality_test'
require 'wongi-engine/filter/inequality_test'
require 'wongi-engine/filter/asserting_test'
require 'wongi-engine/filter/less_than_test'
require 'wongi-engine/filter/greater_than_test'
require 'wongi-engine/filter/greater_than_or_equal_test'
